image: node:lts

cache:
  paths:
    # - node_modules/
    #    wait for https://gitlab.com/gitlab-org/gitlab-runner/issues/2620
    # - packages/**/node_modules/
    # - examples/sample/node_modules/

stages:
  - test
  - test:cov
  - build
  - release
  - deploy

before_script:
  - npx envinfo --registry https://registry.npmmirror.com/
  - yarn install --registry https://registry.npmmirror.com/
  - cd examples/sample
  - yarn install --registry https://registry.npmmirror.com/
  - cd ../..

build:
  stage: build
  script:
    - npm run build
  tags:
    - docker

build-on-node-latest:
  image: node:latest
  stage: build
  script:
    - npm run build
  tags:
    - docker

coverage:
  stage: test:cov
  # https://ac.gerrit.sodajs.org/fe/common-docker
  image: node:lts
  coverage: '/^Lines\s*: (\d+\.\d+)%/'
  script:
    - npm run build:dev # to test coverage, don't minify code
    - npm run test:cov
  artifacts:
    paths:
      - coverage/
    expire_in: 2 weeks
  tags:
    - docker

test:
  stage: test
  image: node:lts
  script:
    - npm run build
    - npm run prettier-check
    - npm run test
  tags:
    - docker

pack:
  stage: release
  script:
    - npm run build
    - npm run pack
    - npm run pack-sourcemaps
  artifacts:
    name: 'hap-toolkit-$CI_COMMIT_REF_NAME'
    paths:
      - 'packages/*/*.tgz'
    expire_in: 2 weeks
  tags:
    - docker
  only:
    - tag
# not supported now
#pages:
#  stage: deploy
#  dependencies:
#    - coverage
#  script:
#    - mv coverage/ public/
#  artifacts:
#    paths:
#      - public
#    expire_in: 90 days
#  tags:
#    - docker
